apiVersion: v1
kind: Service
metadata:
  name: mes-order-service
spec:
  type: ClusterIP
  selector:
    app: mes-order-service
    type: service
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080