apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-order-service
spec:
  replicas: 3 # Number of pods to run
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2  # Max number of extra pods created during the update
      maxUnavailable: 1 # Max number of unavailable pods during the update
  selector:
    matchLabels:
      app: mes-order-service
      type: service
      env: dev
  template:
    metadata:
      labels:
        app: mes-order-service
        type: service
        env: dev
        version: 1.0.0.1-SNAPSHOT
    spec:
      containers:
        - name: mes-order-service
          image: developerhelperhub/mes-order-service:1.0.0.1-SNAPSHOT  # Docker image and Update to a new version of the image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mes-order-service
              topologyKey: "topology.kubernetes.io/zone"